[database]

[database.primary]
database = 'test'
server = "192.168.1.1"
port = 5432
user = 5000
password = true

[database.secondary]
database = 'test'
server = "192.168.1.2"
port = 5432
user = 5000
password = true

[database.tertiary]
database = 'test'
server = "192.168.1.3"
port = 5432
user = 5000
password = true
